GET http://localhost:8000/api/projects

###

GET http://localhost:8000/api/projects/63eaa8876b4e39a21a8c7c1b

###

POST http://localhost:8000/api/projects
Content-type: application/json

{
    "title": "Responsive Design",
    "person": "Liana",
    "due": "2023-05-10",
    "status": "ongoing"
}

###

DELETE http://localhost:8000/api/projects/63eaaa02da631d684c925de3

###

PATCH http://localhost:8000/api/projects/63ebc488ba6e761a9582ed77
Content-type: application/json

{
    "title": "lelele lululu",
    "person": "Christopher",
    "due": "2023-03-23",
    "status": "ongoing"    
}
