GET http://localhost:5000/api/projects

###

GET http://localhost:5000/api/projects/63eaa8876b4e39a21a8c7c1b

###

POST http://localhost:5000/api/projects
Content-type: application/json

{
    "title": "New Navbar",
    "person": "Becky",
    "due": "2023-05-10",
    "status": "ongoing"
}

###

DELETE http://localhost:5000/api/projects/62626
###

PATCH http://localhost:5000/api/projects/262662
Content-type: application/json

{
    "title": "Shoulder Press",
    "load": 10,
    "reps": 50
}
